### PR TITLE
Improve staking input UX

### PR DESCRIPTION
**Pull request by cory-tanner**
### Proposal
- Don't allow users to submit a request if input value is less than or greater than their token balance

If this looks good to the team I will add this functionality to the `UNSTAKING` and `YOUR EARNINGS` sections before this PR is merged

### CODE REVIEW

**Comment by cory-tanner** [comment]
@Sam-Devs Hello! If these UX changes look good to you please let me know before you might merge so I can apply the same UX to the other two sections on this page. The objective is to only let the user stake/unstake/claim what they have in their wallet and eliminating confusion when they enter incorrect values.

**Comment by cory-tanner** [comment]
@Sam-Devs or @Hendobox  I had some time and implement the rest of this UX proposal to the earnings section + unstaking section. These changes should be thoroughly tested before merging. Thanks!

**Comment by Sam-Devs** [comment]
I will go through that.
Thanks.

**Comment by cory-tanner** [comment]
Thanks @Sam-Devs any additional information I can provide to move this PR along?

**Comment by Sam-Devs** [comment]
Let's see how things go this weekend.
I need to do some revamp on the UI.
Thanks.

**Comment by cory-tanner** [comment]
@Sam-Devs If you would like me to review any UI work you do this weekend i'd be happy to provide feedback.

**Pull request merged**
